# Generated by Django 3.2.4 on 2021-06-19 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='nomatch', message='Minimum length has to be 6', regex='^.{6}$')]),
        ),
    ]
