# Generated by Django 3.2.4 on 2021-09-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_alter_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
