# Generated by Django 3.2.4 on 2021-09-02 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_alter_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Minimum length has to be 6', regex='^.{6}$')]),
        ),
    ]
