# Generated by Django 3.2.4 on 2021-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0004_alter_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='color',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
