# Generated by Django 3.2.4 on 2021-09-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0005_auto_20210910_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
