# Generated by Django 3.2.4 on 2021-08-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_productcategory_productsubcategory'),
        ('products', '0003_auto_20210810_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='properties.ProductCategory'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(to='properties.ProductCollection'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(to='properties.ProductSubCategory'),
        ),
    ]
