# Generated by Django 3.2.4 on 2021-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_media_tags'),
        ('products', '0006_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ManyToManyField(blank=True, to='media.Media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
