# Generated by Django 3.2.4 on 2021-09-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_media_options'),
        ('colors', '0006_alter_color_options'),
        ('products', '0007_auto_20210910_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorvariationforproducts',
            options={'verbose_name': 'Variação de cor', 'verbose_name_plural': 'Variações de cor'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='colorvariationforproducts',
            name='media',
            field=models.ManyToManyField(blank=True, to='media.Media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_variations',
            field=models.ManyToManyField(blank=True, through='products.ColorVariationForProducts', to='colors.Color'),
        ),
    ]
