# Generated by Django 3.2.4 on 2021-09-13 23:46

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_media_options'),
        ('products', '0008_auto_20210913_1938'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='colorvariationforproducts',
            name='media',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='media.Media'),
        ),
        AlterSortedManyToManyField(
            model_name='product',
            name='media',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='media.Media'),
        ),
    ]
