# Generated by Django 3.2.4 on 2021-08-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_productcategory_productsubcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStyle',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
