# Generated by Django 3.2.4 on 2021-09-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210819_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediastyle',
            options={'verbose_name': 'Estilo', 'verbose_name_plural': 'Estilos'},
        ),
        migrations.AlterModelOptions(
            name='mediatype',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='productcollection',
            options={'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name': 'Sub-categoria', 'verbose_name_plural': 'Sub-categorias'},
        ),
    ]
