# Generated by Django 3.2.4 on 2021-09-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210913_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
