# Generated by Django 3.2.4 on 2021-09-16 18:59

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_media_options'),
        ('books', '0004_alter_book_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='media',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='media.Media'),
        ),
    ]
