# Generated by Django 3.2.4 on 2021-06-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('media_type', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=100)),
                ('is_private', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
