# Generated by Django 3.2.4 on 2021-06-12 22:48

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
