# Generated by Django 3.2.4 on 2021-08-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_productcategory_productsubcategory'),
        ('media', '0002_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.mediatype'),
        ),
        migrations.AlterField(
            model_name='media',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.mediastyle'),
        ),
    ]
