# Generated by Django 3.2.4 on 2021-09-02 02:50

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20210812_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default='socialist_dog.jpg', upload_to=media.models.upload_to),
        ),
    ]
