# Generated by Django 3.2.4 on 2021-09-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_media_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Mídia', 'verbose_name_plural': 'Mídias'},
        ),
    ]
